on:
  push:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      #- run: echo "Hello world"
      #- run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...

  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'

      - name: Verify formatting
        run: |
          no_unformatted_files="$(gofmt -l $(git ls-files '*.go') | wc -l)"
          exit "$no_unformatted_files"
